name: Install and activate ExpressVPN
inputs:
  activation-code:
    required: true
runs:
  using: "composite"
  steps:
      - run: |
          sudo apt update
          sudo apt install -y expect
          wget -O expressvpn_3.69.0.0-1_amd64.deb https://www.expressvpn.works/clients/linux/expressvpn_3.69.0.0-1_amd64.deb && sudo dpkg -i expressvpn_3.69.0.0-1_amd64.deb && sudo apt-get install -f -y && rm expressvpn_3.69.0.0-1_amd64.deb
          chmod +x .github/actions/vpn/activate_vpn.sh
          .github/actions/vpn/activate_vpn.sh ${{ inputs.activation-code }}
        shell: bash